### ISSUE TITLE
[TASK] publish StreamGen

### ISSUE THREAD

**Issue by LaurenzBeck** [Infineon/StreamGen#1]
## ✅ Task

After receiving the final green lights from Infineon, I want to perform some finishing touches for the release

### 📃 Checklist

- [x] add license
- [x] setup community standards
- [x] host documentation on github pages
- [x] setup towncrier
- [x] release 1.0.0
- [x] publish on pypi
